Tweak tcb-action.yml

diff --git a/.github/workflows/tcb-action.yml b/.github/workflows/tcb-action.yml
--- a/.github/workflows/tcb-action.yml
+++ b/.github/workflows/tcb-action.yml
@@ -16,6 +16,5 @@ on:
 jobs:
   run:
     steps:
-      - name: "Fail because TCB is modified"
-        id: tcb_fail
-	run: echo "TCB modified -- automatic failure" ; exit 1
+      - name: 'Fail because TCB is modified'
+	run: echo 'TCB modified -- automatic failure' ; exit 1
